### ISSUE TITLE
nm-applet doesn't show up anymore

### ISSUE THREAD

**Issue by ytzemih** [csxr/i3-gnome#25]
Hi there, 

awesome plugin. 

However, when choosing Gnome+i3 session in GDM, the nm-applet does no more show up in the i3 status bar. It does for me when just using a plain i3 session. 

I am using Ubuntu 18.04.

Thanks for your help.

**Comment by ytzemih** [comment]
Hi, 

yes, that's how the section of my config looks like:
```
...
exec --no-startup-id "xrandr --output eDP-1 --primary"
...
exec --no-startup-id /usr/lib/gnome-settings-daemon/gsd-xsettings
exec_always --no-startup-id gnome-power-manager
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id gnome-flashback
exec_always --no-startup-id nm-applet 
...
bar {
        tray_output primary
        status_command i3status -c ~/.config/i3/i3status.conf
}
```
I tried to put the bar statement before the execs but it didn't change anything. Additionally, when I start nm-applet in my console nothing happens. However, in my i3 only session it works as expected.

**Comment by jcstr** [comment]
Sorry for my late answer,

Well, definitely it's an strange behavior, let me get more info about `nm-applet` and similar issues.

**Comment by ytzemih** [comment]
It's alright. Thanks.

**Comment by jcstr** [comment]
@ytzemih, 
I just reproduced your situation and it result the same for me, so, my first thoughts are that some GNOME components are doing something that modifies the behavior of i3, and my recent experience of something like that was about adding `gnome-flashback` to the config, and the wallpaper started to get managed by GNOME, so, could you hide `gnome-flashback` of your i3 config and share what happens?

**Comment by muktupavels** [comment]
It is simply not autostarted anymore under GNOME:
https://gitlab.gnome.org/GNOME/network-manager-applet/commit/2a7336451cb6f066dd7ea80bf9faed40881b0ebf

If you have installed `gnome-flashback` and `DesktopNames` include `GNOME-Flashback` then it should be autostarted, because `gnome-flashback` installs custom autostart file:
https://gitlab.gnome.org/GNOME/gnome-flashback/blob/master/data/autostart/gnome-flashback-nm-applet.desktop.in

Other option might be to start manually or you could try to add `nm-applet` to RequiredComponents, but I don't remember what `gnome-session` does if desktop file has NotShowIn=GNOME. It still might not be started...

**Comment by jcstr** [comment]
> It is simply not autostarted anymore under GNOME:
gitlab.gnome.org/GNOME/network-manager-applet/commit/2a7336451cb6f066dd7ea80bf9faed40881b0ebf

oh, i didn't noticed that, thanks for sharing.

> Other option might be to start manually or you could try to add nm-applet to RequiredComponents, but I don't remember what gnome-session does if desktop file has NotShowIn=GNOME. It still might not be started...

I think that [this](https://github.com/jcstr/i3-gnome/blob/master/session/i3-gnome.session) can be adapted to do so.

I'll do the test and check if it works.

**Comment by ytzemih** [comment]
@jcstr Hi, sorry for my late answer: Excluded the gnome-flashback line from my i3 config and restarted gdm and the session, same behaviour: no nm-applet (probably unsurprising in presence of @muktupavels hint). I guess I can't be of any help at the moment. Thanks for checking a fix, anyway.

**Comment by arnuschky** [comment]
I have the same problem. Any luck with this?

@ytzemih I am using Ubuntu 18.04 too. However it uses Gnome 3.28 - not sure if that's relevant (this project's requirements say it needs Gnome 3.30).

**Comment by arnuschky** [comment]
Starting nm-applet yields the following error:

```
(nm-applet:7427): Gtk-WARNING **: 21:42:17.189: Can't set a parent on widget which has a parent

(nm-applet:7427): Gtk-CRITICAL **: 21:42:21.872: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

(nm-applet:7427): Gtk-CRITICAL **: 21:42:21.872: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by arnuschky** [comment]
@ytzemih by any chance did you upgrade too from 16.04?

**Comment by arnuschky** [comment]
I solved this by starting all notification area applets using `dbus-launch`. For example for starting nm-applet from my `.i3/config`:

`exec --no-startup-id dbus-launch nm-applet`

**Comment by ytzemih** [comment]
@arnuschky I did a new 18.04 install. Got the same error, but your last suggestion also works for me. Thanks! `dbus-launch` is the key :)

**Comment by tenllado** [comment]
Hi:

I solved this by changing the DesktopNames entry in the i3-gnome.desktop to

DesktopNames=GNOME-Flashback;GNOME;

This way, when the session starts all the applications in /etc/xdg/autostart, that are configured to start with the gnome-flashback session, also start with the i3-gnome session. At least on debian, you have one that is for the nm-applet (gnome-flashback-nm-applet.desktop),

**Comment by kunniva** [comment]
@tenllado thanks, it worked for me :)

**Comment by csxr** [comment]
due to resolution to this issue, is closed now.
