### ISSUE TITLE
REQUEST: BSPWM instead of i3?

### ISSUE THREAD

**Issue by shizonic** [csxr/i3-gnome#28]
Would it be possible to use bspwm instead of i3?

**Comment by csxr** [comment]
Yes it is, there's actually a fork focusing on BSPWM, let me find out.

**Comment by shizonic** [comment]
Thank you for your quick reply.

This would be awesome if you could find this fork. I was planning to create a bspwm fork too, but ifthere is already one I don't have to to reinvent the wheel. In any way: You did a great job and I appreciate it! Thank you.

**Comment by csxr** [comment]
hmm, it seems like it's not available nor exist, i remember that one of the forks was trying to add a bspwm support but i don't know exactly what happened, i'll try to find out but if you wish you could start your fork, no one knows.

**Comment by csxr** [comment]
No problem!, go ahead it would be nice to have more options out there.

Cheers!

**Comment by shizonic** [comment]
@csxr Just a question. Did you get gnome-tweak-tool working with gnome-flashback?

**Comment by csxr** [comment]
Yes, but to be honest i don't have hard customizations, just something simple.

**Comment by shizonic** [comment]
Okay... Weird. I still get the `Error calling GetCurrentState: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Mutter.DisplayConfig" does not exist` error even with `gnome-flashback`. All settings (including the monitors tab) works without any problems, but `gnome-tweak-tool` doesn't. :/

**Comment by csxr** [comment]
You should consider that this tweak has been working successful under the last version of GNOME 3.30 and `gnome-flashback` is not a main focus

**Comment by shizonic** [comment]
Yes but neither if I use official gnome nor if I use gnome-flashback gnome-tweak-tool works. I am using latest GNOME (3.30) in both cases.

**Comment by csxr** [comment]
Closing this non-issue due to lack of activity.
