### ISSUE TITLE
GDM Login doesn't run .config/i3/config

### ISSUE THREAD

**Issue by unpragmatic** [csxr/i3-gnome#32]
I'm using GDM to login with i3 + gnome.

However, when I login it doesn't look like my config file gets run. I figure its a problem
with the config file not running because my `exec_aways feh ....` command and `setxkbmap...`
command do nothing however if I restart i3 using `i3-msg restart` both commands get run.

Any hints? I'm guessing it doesn't pick up on my i3 config due to the session files but I'm
not too familiar with how that works.

Note that selecting i3 with GDM works fine.

**Comment by csxr** [comment]
On my `.config/i3/config` a have this options to get run any instance:
```
exec_always --no-startup-id feh --randomize --bg-fill ~/Pictures/walls
exec_always --no-startup-id compton -bc
```

The `--no-startup-id` flag can help to run any software inside i3.
This may help you.

Cheers!

**Comment by unpragmatic** [comment]
I have the same options, it just doesn't appear to work.
However, when I run `i3-msg restart` it works.

**Comment by csxr** [comment]
How exactly did you notice that `GDM` itself doesn't pick up the i3 config file?
I have understood that GDM handles the login screen and nothing more.
This is the first time that this behavior is mentioned.

**Comment by unpragmatic** [comment]
Its noticeable because feh doesn't run til I run i3-msg restart

**Comment by csxr** [comment]
Make sure you have both `feh` and `setxkbmap` on `.xinitrc` file because this will indicate to xorg (not GDM) to run these commands as included in the session.

If the issue persists you can try `eval $(cat ~/.fehbg)` by adding it to the i3 config file.

**Comment by unpragmatic** [comment]
Ah, found the problem. Some of the previous commands failed preventing feh and setxkbmap from running. These were the gnome tools mentioned in the tips and tricks section.

**Comment by unpragmatic** [comment]
Actually, that wasn't quite right. It looks like running gnome-flashback either before or after feh and setxkbmap prevents their effects.

**Comment by csxr** [comment]
Again, did you read this?

> Make sure you have both feh and setxkbmap on .xinitrc file because this will indicate to xorg (not GDM) to run these commands as included in the session.
> If the issue persists you can try eval $(cat ~/.fehbg) by adding it to the i3 config file.

`setxkbmap` is part of Xorg's ecosystem, `feh` can be considered as another individual component, the issue doesn't make sense, you're taking something general instead of this particular case.

is _your_ `xinitrc` running?
Add:
`echo running > isitworking.txt`
Right above or below it, and after starting x check that file. If it exists and has `running` in it, it's good.

RTFM:
- https://wiki.archlinux.org/index.php/Xorg
