### ISSUE TITLE
gnome-control-center doesn't provide fractional scaling

### ISSUE THREAD

**Issue by jantonioperez** [csxr/i3-gnome#33]
I'm using Ubuntu 19.04 with gnome version 3.32.1. I have a high-dpi monitor and I enabled fractional scaling in gnome using
```
gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"
```
Under the normal ubuntu UI in gnome-control-center, this provides the option of scaling windows by either 125%, 150%, and 175%, in addition to the regular scaling options of 100% and 200%. 

However, in i3-gnome, I no longer have those options (and I only see either 100% or 200%). Is there any way to enable fractional scaling in i3-gnome, so that I can scale things on my monitor by 150%?

**Comment by antenore** [comment]
I've the same problem.
I may be wrong but I think that it doesn't work because mutter is not running.

i3wm is an X11 window manager and mutter, under X11, it's WM as well and you cannot have two WM running at the same time on the same display (X.Org display).

I don't thin there is a solution to this

**Comment by jantonioperez** [comment]
I can set the scaling from 100% to 200% using the gnome control center, and that works without issue. It's only fractional scaling that isn't shown as an option. Is there something else I can change, such as the dpi given in a configuration file?

**Comment by antenore** [comment]
@jantonioperez did you read my comment? The fractional scaling has been implemented only in mutter and mutter cannot run at the same time as i3wm.

So you cannot have fractional scaling through gnome, but you can using some workaround and randr

Even if you are on Ubuntu, read this https://wiki.archlinux.org/index.php/HiDPI

**Comment by csxr** [comment]
According to @antenore, you can either workaround or use `randr`.

https://wiki.archlinux.org/index.php/Xrandr

You **cannot** run 2 window managers at the same time.

> I don't thin there is a solution to this

There's not.
