### ISSUE TITLE
Request: Port i3-gnome to work with Sway

### ISSUE THREAD

**Issue by whooperr** [csxr/i3-gnome#35]
It'd be great if this was compatible with sway wm. Any chance on porting it to work with it?

**Comment by csxr** [comment]
Well, I think that there's a way to get `sway` compatible with GNOME but you'll have to read a lot.

On another issue (#28) someone were trying to get it work with BSPWM, I've not knew anything new after closing the issue (due lack of activity).

I friendly invite you to try and implement `sway-gnome` by your self, you can use all the documentation available and everything related with the scripts.

The main challenge you'll face will be get to understand how wayland works and how can relate it with the binaries of GNOME.

These days i3-gnome have been a reference to customize and relate i3 and GNOME.

I hope the wiki we have here can give you a hand on this.

I'm looking forward with other projects so my time is limited on dealing with the issues of i3-gnome and update it in case GNOME updates as well.
